### ISSUE TITLE
RTF file support 

### ISSUE THREAD

**Issue by rakibhossensweet** [Cuperino/QPrompt-Teleprompter#234]
I see rtf file is not supported in QPrompt-Teleprompter.
I hope you will add that support

**Comment by Cuperino** [comment]
Hi @rakibhossensweet,

Support for RTF has already been added in QPrompt's development builds for what will become v1.2. To use the feature you need a copy of LibreOffice installed in your computer, since that takes care of doing the format conversion in the background.

Due to technical constraints, you cannot be running LibreOffice while opening an RTF in QPrompt.

You can get development builds of QPrompt with this feature from [Patreon](https://www.patreon.com/qpromptapp) by supporting the project economically. Or you could [build it from source](https://github.com/Cuperino/QPrompt-Teleprompter/blob/main/build.md) by yourself, which I will warn takes effort, but it's worth doing if you'd like quick access to the latest features and bug fixes.

**Comment by Cuperino** [comment]
Closing as already implemented.
