### ISSUE TITLE
Unable to open multiple instances with unique scripts

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#239]
**Bug Description**
Upon saving a second instance of QPROMPT with a unique script, the first instance changes to match the second.

**Expected behavior**
Instances should preserve unique contents like multiple Word documents.

**Device information**
 - QPrompt Version: 1.2 r6
 - Operating System: Raspberry Pi Bookworm, latest updates.

**Comment by Cuperino** [comment]
When you say unique script, you mean these scripts have been saved to uniquely different files? I see no reason why this should happen when working on separate files, because each instance of QPrompt is completely independent from the others.

Assuming that what you say is correct, I suspect that the two instances might have both opened the same file at some point of their execution, and later opened a different file on at least one of the instances. That would mean there's a bug with the file watcher.

Does my hypothesis match your experience?

**Comment by videosmith** [comment]
Completely different files.
Created the first instance, loaded/edited/saved a file.
Created a second instance, loaded/edited a second file. Upon saving, both instances identical as far as i can determine.
    On Friday, January 5, 2024 at 12:51:49 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


When you say unique script, you mean these scripts have been saved to uniquely different files? I see no reason why this should happen when working on separate files, because each instance of QPrompt is completely independent from the others.

Assuming that what you say is correct, I suspect that the two instances might have both opened the same file at some point of their execution, and later opened a different file on at least one of the instances. That would mean there's a bug with the file watcher.

Does my hypothesis match your experience?

**Comment by videosmith** [comment]
It seems to occur when scripts have been previously loaded and edited/saved.

**Comment by videosmith** [comment]
Perhaps linked to the ability to load the last script upon launching somehow? Even though the app instances are already launched?

**Comment by Cuperino** [comment]
> Perhaps linked to the ability to load the last script upon launching somehow? Even though the app instances are already launched?

I think this could be it. Making as a bug for now, tho I haven't had the chance to replicate.

**Comment by Cuperino** [comment]
Issue replicated and fixed
