### ISSUE TITLE
Hamburger menu error in full screen

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt-Teleprompter#248]
**Bug Description**
When attempting to access the upper-left Hamburger menu in full screen, another contextual menu appears, only works correctly if you click the very bottom of the Hamburger menu.

**Steps to Reproduce**
1. Click the menu in windowed mode, left side menu appears as expected.
2. Enter full screen mode, repeat step 1, a different menu appears
3. Click at the very bottom of the Hamburger, left side menu appears as expected.

**Expected behavior**
Should work correctly windowed and full screen.

**Screenshots** (optional)
![Screenshot_20240327_173740](https://github.com/Cuperino/QPrompt-Teleprompter/assets/88691671/84e31bf8-fd89-4b94-a693-06a5308c8f30)

![Screenshot_20240327_181019](https://github.com/Cuperino/QPrompt-Teleprompter/assets/88691671/213dda76-2cc7-43f5-8013-cd73e33d323d)

![Screenshot_20240327_181210x](https://github.com/Cuperino/QPrompt-Teleprompter/assets/88691671/95c4513b-da61-422a-bb39-d3607801b78f)

**Device information**
 - QPrompt Version: 1.2 v6
 - Operating System: Debian 12.5 AMD x64, Plasma/Wayland, latest updates

**Comment by Cuperino** [comment]
That context menu doesn't look like it's part of QPrompt. I suspect this is a bug with the window manager or desktop environment, which is triggering another program when you click in that area while in full screen.

The other program looks like a clipboard manager that I've used previously. I suspect that it has a window or widget of some kind that is being mistakenly placed to the top left of the screen, but it isn't drawn because technically it's supposed to be off-screen (in the tray area) or because the full screen window is covering it.

If the issue is still going, you should be able to replicate it with a program other than QPrompt, by putting it in full screen and clicking in the same area.
