### ISSUE TITLE
App fails to start on recent and up-to-date Mac

### ISSUE THREAD

**Issue by paulmsander** [Cuperino/QPrompt-Teleprompter#262]
**Are you ready to report?**

Before reporting a bug, use GitHub's [issues filter](https://github.com/Cuperino/QPrompt/issues) to see if the bug you've found was already reported. If it has been reported, please indicate said bug also affects you and provide details that add value to the discussion. If the bug hasn't been reported, please continue to fill out this form.

**Bug Description**

"Application is damaged and won't open" on recent and up-to-date Mac.  Mac Studio 2023 (Apple M2 Ultra chip, 64 GB memory, macOS Sonoma 14.5 (23F79))

**Steps to Reproduce**
1.  Download the dmg file using Safari
2. Move the dmg file to an empty folder
3. Double-click the dmg file
4. Move the application icon to the Applications folder (needs admin user authentication)
5. Copy the application icon to the dock
6. Double-click the application icon in the dock
7. Become annoyed by the error message quoted in the bug description

**Expected behavior**

I expect to see the application running in step 7.

**Detailed description of display configuration** (if applicable)

Apple Studio Display

**Screenshots** (optional)

n/a

**Device information**
 - QPrompt Version:  qprompt-v1.1.6-51788eb-macos-clang-x86_64.dmg
 - Operating System: macOS Sonoma 14.5 (23F79)

**Additional context**

This was the first time I downloaded and installed the application.  My user account is unprivileged, and it's not an administration account.  I was prompted for an administrator's password, which I gave correctly.

I did not see the usual warning that the application was downloaded from the Internet, and the prompt as to whether or not I should trust it anyway.

**Comment by Cuperino** [comment]
Hi @paulmsander 

Thank you for filing this issue. It has already been reported so I'm going to have to close this one as a duplicate. Here is the original report, it contains information on how to work around the problem: https://github.com/Cuperino/QPrompt-Teleprompter/issues/150

In order to address the issue, I'm in the process of re-creating the entire build pipeline. A status report on this can be found on the following public Patreon blog post: https://www.patreon.com/posts/106234846
