### ISSUE TITLE
Beeing able to make the prompting area slimmer from booth sides

### ISSUE THREAD

**Issue by Liebeg** [Cuperino/QPrompt-Teleprompter#266]
**Is your feature request related to a problem or a limitation? Please describe...**
You can currently make the area the text is beeing display slimmer only from by dragging the line on the left side towards the middle. I would like to be able to grab and push either the left or the right line towards the middle whilst the other side keeps doing the same thing.

**Describe alternatives you've considered**
I jus't want the way the left line behaves copied to the right line. There haven't been any other alternatives i have considered.

**Provide use examples**
It makes using QPromt more simpler since you don't have to keep in mind you can only adjust it via the left not the right line.

![image](https://github.com/Cuperino/QPrompt-Teleprompter/assets/95579941/057dbd0f-9f60-43a7-84ce-30dd31ebd9f3)
![image](https://github.com/Cuperino/QPrompt-Teleprompter/assets/95579941/e0e75be4-0d90-4df9-b2aa-971ddeb7cd31)

booth should behave the same way

**Comment by Cuperino** [comment]
Each handle serves a different purpose.  The right side handle serves the purpose of displacing contents horizontally.  This isn't self evident when the prompter contents are at full width.  Each handle has mouse cursors that reflect what you can do with them at different times.  That is, unfortunately, too subtle for some users to notice.

I won't make both handles behave in the same way, but if you have other suggestions they're also welcome.

Also, FYI, the roles of the handles are flipped when the UI is switched to a Right to Left writing system.  For that reason I struggle with referring to them as a left or right handle, but I haven't come up with a better naming scheme...

**Comment by Cuperino** [comment]
To my understanding people expect to use the right handle in the same way as the left handle because they weren't able to use the right handle from the program's initial state, which made it seem like it does nothing. This is no longer the case in QPrompt v2.0, which increases discoverability of what the right handle actually does.

Since each handle serves a different purpose and that purpose is now easily discoverable for both handles, I'm going to close this issue as "wont fix" because making both handles have both resizing and move behaviors would make interacting with the handles more complicated than it needs to be for users.
